import os
import cv2
import numpy as np
#import tensorflow as tf
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()
import sys
sys.path.append("..")
# from utils import label_map_util
# from utils import visualization_utils as vis_util
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from time import sleep

class Ui_MainWindow(object):
    
    
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 650, 981, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.centralwidget.showMaximized()
        
        self.layoutBot = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.layoutBot.setContentsMargins(0, 0, 0, 0)
        self.layoutBot.setSpacing(10)
        self.layoutBot.setObjectName("layoutBot")
        self.threshold_groupbox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.threshold_groupbox.setFont(font)
        self.threshold_groupbox.setObjectName("threshold_groupbox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.threshold_groupbox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.threshold_spinbox = QtWidgets.QSpinBox(self.threshold_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_spinbox.sizePolicy().hasHeightForWidth())
        self.threshold_spinbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshold_spinbox.setFont(font)
        self.threshold_spinbox.setMinimum(1)
        self.threshold_spinbox.setObjectName("threshold_spinbox")
        self.horizontalLayout_7.addWidget(self.threshold_spinbox)
        self.threshold_btn = QtWidgets.QPushButton(self.threshold_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_btn.sizePolicy().hasHeightForWidth())
        self.threshold_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshold_btn.setFont(font)
        self.threshold_btn.setObjectName("threshold_btn")
        self.horizontalLayout_7.addWidget(self.threshold_btn)
        self.layoutBot.addWidget(self.threshold_groupbox)
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.start_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.layoutBot.addWidget(self.start_btn)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 981, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        
        self.layoutTop = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.layoutTop.setContentsMargins(0, 0, 0, 0)
        self.layoutTop.setSpacing(4)
        self.layoutTop.setObjectName("layoutTop")
        self.efb_counter_groupbox = QtWidgets.QGroupBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.efb_counter_groupbox.setFont(font)
        self.efb_counter_groupbox.setObjectName("efb_counter_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.efb_counter_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.efb_counter = QtWidgets.QLCDNumber(self.efb_counter_groupbox)
        self.efb_counter.setAutoFillBackground(False)
        self.efb_counter.setFrameShape(QtWidgets.QFrame.Box)
        self.efb_counter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.efb_counter.setLineWidth(1)
        self.efb_counter.setSmallDecimalPoint(False)
        self.efb_counter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.efb_counter.setObjectName("efb_counter")
        self.verticalLayout_2.addWidget(self.efb_counter)
        self.layoutTop.addWidget(self.efb_counter_groupbox)
        self.not_efb_counter_groupbox = QtWidgets.QGroupBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.not_efb_counter_groupbox.setFont(font)
        self.not_efb_counter_groupbox.setObjectName("not_efb_counter_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.not_efb_counter_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.not_efb_counter = QtWidgets.QLCDNumber(self.not_efb_counter_groupbox)
        self.not_efb_counter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.not_efb_counter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.not_efb_counter.setObjectName("not_efb_counter")
        self.verticalLayout_3.addWidget(self.not_efb_counter)
        self.layoutTop.addWidget(self.not_efb_counter_groupbox)
        self.total_groupbox = QtWidgets.QGroupBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.total_groupbox.setFont(font)
        self.total_groupbox.setObjectName("total_groupbox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.total_groupbox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.total_counter = QtWidgets.QLCDNumber(self.total_groupbox)
        self.total_counter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.total_counter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.total_counter.setObjectName("total_counter")
        self.horizontalLayout_6.addWidget(self.total_counter)
        self.layoutTop.addWidget(self.total_groupbox)
        self.efficiency_groupbox = QtWidgets.QGroupBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.efficiency_groupbox.setFont(font)
        self.efficiency_groupbox.setObjectName("efficiency_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.efficiency_groupbox)
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.efficiency_counter = QtWidgets.QLCDNumber(self.efficiency_groupbox)
        self.efficiency_counter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.efficiency_counter.setSmallDecimalPoint(True)
        self.efficiency_counter.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.efficiency_counter.setProperty("value", 100.0)
        self.efficiency_counter.setObjectName("efficiency_counter")
        self.verticalLayout_4.addWidget(self.efficiency_counter)
        self.layoutTop.addWidget(self.efficiency_groupbox)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 100, 961, 541))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        
        self.layoutMid = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.layoutMid.setContentsMargins(0, 0, 0, 0)
        self.layoutMid.setObjectName("layoutMid")
        self.labelFeed = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelFeed.setPixmap(QtGui.QPixmap("img/front.jpg"))
        self.labelFeed.setScaledContents(True)
        self.labelFeed.setObjectName("labelFeed")
        self.layoutMid.addWidget(self.labelFeed)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.threshold_groupbox.setTitle(_translate("MainWindow", "EFB Fruit Count Threshold"))
        self.threshold_btn.setText(_translate("MainWindow", "Set Threshold"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.efb_counter_groupbox.setTitle(_translate("MainWindow", "Empty Fruit Bunch"))
        self.not_efb_counter_groupbox.setTitle(_translate("MainWindow", "Not Empty Fruit Bunch"))
        self.total_groupbox.setTitle(_translate("MainWindow", "Total Analysed"))
        self.efficiency_groupbox.setTitle(_translate("MainWindow", "Efficiency Rate (%)"))
        self.labelFeed.setText(_translate("MainWindow", "TextLabel"))